### ISSUE TITLE
Restrict avatar uploading to verified members only

### ISSUE THREAD

**Issue by erichowey** [erichowey/vgphotohunt#5]
To reduce crap getting uploaded. I think you should only be able to upload avatars and fill out your user profile after you've verified your email. Tagging as RFC because I'm not sure if everyone agrees with me on this.

**Comment by brandonvogt** [comment]
I agree.

**Comment by erichowey** [comment]
I also feel voting should be restricted to registered users only as well. People could easily make puppet accounts to skew the numbers.
